name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Hello world
      uses: actions/hello-world-javascript-action@v1.1 # Name of the action. This uses https://github.com/actions/hello-world-javascript-action
      with:                                            # This section is needed if you need to pass arguments to the action
        who-to-greet: 'Mona the Octocat'

      runs: 'dotnet build`
      runs: 'cd'
      runs: 'cd DotnetTemplate.Web'
      runs: 'npm install'
      runs: 'dotnet test'
      runs: 'npm t'
      runs: 'npm run lint'
